CREATE TABLE IF NOT EXISTS `prompt` (
    `prompt_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `secuence` INT NULL,
    `code` VARCHAR(80) NOT NULL,
    `name` VARCHAR(150) NOT NULL,
    `description` VARCHAR(500) NULL,
    `agent` VARCHAR(100) NULL,
    `agent_group` VARCHAR(200) NOT NULL,
    `type` VARCHAR(50) NULL,
    `llm_model` VARCHAR(100) NULL,
    `version` VARCHAR(20) NOT NULL DEFAULT '1.0',
    `system_prompt` TEXT NOT NULL,
    `user_prompt` TEXT NULL,
    `temperature` DECIMAL(3, 2) NULL DEFAULT 0.20,
    `max_tokens` INT NULL,
    `active` TINYINT(1) NULL DEFAULT 1,
    `observations` TEXT NULL,
    `created_by` VARCHAR(100) NULL,
    `created_at` DATETIME NULL,
    `updated_by` VARCHAR(100) NULL,
    `updated_at` DATETIME NULL,
    `schema_output` TEXT NULL,
    PRIMARY KEY (`prompt_id`),
    KEY `idx_prompt_agent_group` (`agent_group`),
    KEY `idx_prompt_code` (`code`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;